name: Pull Request Validation

on: 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Lint code
      run: npm run lint
      
    - name: Run tests
      run: npm run test